blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [

    path('', views.home, name='acceuil'),
    path('reseau/', views.reseau, name='reseau'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('pooldev/', views.pooldev, name='pooldev'),
    path('article/', views.article, name='article'),
    path('reseau/listeconfig/', views.listeconfig, name='listeconfig'),
    path('reseau/ajoutconfig/', views.ajoutconfig, name='ajoutconfig'),
    path('navbar/', views.navbar, name='navbar'),
    path('slider/', views.slider, name='slider'),
    path('footer/', views.footer, name='footer'),
    path('header/', views.header, name='header'),

    

]

monprojet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views





app_name='users'


urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('deconnect/', views.deconnect, name='deconnect'),
    path('login/', views.login, name='login'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.





class Superviser(models.Model):
    equipement = models.ImageField(upload_to="equipement", null=True, blank=True)
    types = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(default=timezone.now, verbose_name="Date de parution")
    
    
    def __str__(self):
       
        return 'configuration'+' '+self.types

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.




class Users(models.Model):

  user = models.OneToOneField(User, on_delete=models.CASCADE)

  def __str__(self):
       
        return self.username







  

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages 
from django import forms
from .models import *
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from .form import ConfigurationForm




# Create your views here.





def home(request):
    
    return  render(request,'blog/acceuil.html')





@login_required
def reseau(request):
    title="Reseau"
    return  render(request,'blog/reseau.html',locals())


@login_required
def maintenance(request):
    return  render(request,'blog/maintenance.html',{'title': 'Maintenance'})


@login_required
def pooldev(request):
    return  render(request,'blog/pooldev.html',{'title': 'PoolDev'})





def article(request):

     return  render(request,'blog/article.html',{'title': 'Article'})


def listeconfig(request):
     configs=Superviser.objects.all()
     title="Reseau-Listconfig"
     return  render(request,'blog/listeconfig.html', locals())


  


def ajoutconfig(request):
     send = False
     form = ConfigurationForm(request.POST,request.FILES)
     if form.is_valid():
          form.save()
          return redirect('/reseau/listeconfig/')
     title="Reseau-AjoutConfig"
     return  render(request,'blog/ajoutconfig.html',locals())



def navbar(request):

     return  render(request,'blog/navbar.html',{'title': 'Navbar'})




def slider(request):

     return  render(request,'blog/slider.html',{'title': 'slider'})



def footer(request):

     return  render(request,'blog/footer.html',{'title': 'footer'})




def header(request):

     return  render(request,'blog/header.html',{'title': 'header'})






  



  

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login
from django.contrib.auth import login as auth_login
from .models import *
from django.contrib.auth import logout
from django.shortcuts import redirect



# Create your views here.





def login(request):


    title = 'login'
    return  render(request,'users/login.html',locals())



def signup(request):
    username_error = password_error = password_length_error = name_error = False 
    title = 'signup'

    if(request.POST):
        email = request.POST['email']
        password = request.POST['password']
        repass = request.POST['repass']
        name = request.POST["name"]
        if (len(name) < 5):
            name_error = True
        if (len(password) < 6):
            password_length_error = name_error = True
        elif password != repass:
            password_error = True
        else:
            users = User.objects.all()
            for user in users:
                if user.username == email:
                    username_error = True
            if not username_error:
                new_user = User.objects.create_user(email, email, password)
                # new_user.name = name
                user = Users()
                user.user = new_user
                # user.name = name
                user.save()

                #new_user = authenticate(email=email, password=password)
                #dj_login(request, new_user)

                return redirect('users:login')
        
    return  render(request,'users/signup.html',{'title': 'inscription'})



def login(request):
    username_error = password_error = error = False
  
    if request.POST:
        email = request.POST["email"]
        password = request.POST["password"]

        if (len(password) < 6):
            password_error = True

        users = User.objects.all()
        
        user = authenticate(username=email, password=password)
        if user is not None:
            dj_login(request, user)
            error = True
            if request.GET.get('next', False):
                return redirect(request.GET['next'])
            else:
                return redirect("/")
        else:
            error = True
    return render(request, 'users/login.html', {'title': 'connexion'})



def deconnect(request):
   logout(request)
   return redirect('/')



def profile(request):
    title = 'profile'
    return  render(request,'users/profile.html',locals())

blog/templates/blog/acceuil.html
 {% extends "blog/base.html" %}
 {% load static %}

 <link href="{% static 'acceuil/acceuil.css' %}" rel="stylesheet">
 <link rel="stylesheet" href="{% static 'acceuil/image.css' %}" >

 
 {% block content %}

 {% include 'blog/slider.html' %}


 <div class="container"  id="content">
       
     
 <h1 class=" mb-5"> <style> body { color: rgb(211, 43, 226); }</style> Plateforme De Gestion d'Equipements De La DSI  LaPoste  </h1>
     
    <div class="row ">


        <div class="col-md-4 paddingTB20">       
              <div class="col-md-12 text-center">
                <img src="{% static 'imagesreseau/dsi4.jpg' %}" class="images" class="img-responvie" alt="">   
            </div>
         </div>




        <div class="col-md-4 paddingTB20">              
            <div class="col-md-12 text-center">
              <img src="{% static 'imagesreseau/dsi6.jpg' %}" class="images" class="img-responvie" alt="">   
            </div>
         </div>
 




        
        <div class="col-md-4 paddingTB20">                 
            <div class="col-md-12 text-center">
                <img src="{% static 'imagesreseau/dsi8.png' %}"  class="img-responvie" alt="">   
          </div>
        </div>  





        <div class="col-md-4 paddingTB20">                 
            <div class="col-md-12 text-center">
                <img src="{% static 'imagesreseau/dsi7.jpg' %}"  class="img-responvie" alt="">   
          </div>
         </div> 
 



        <div class="col-md-4 paddingTB20">               
            <div class="col-md-12 text-center">
               <img src="{% static 'imagesreseau/dsi5.jpg' %}" class="images" class="img-responvie" alt="">   
           </div>
        </div>




        <div class="col-md-4 paddingTB20">                 
            <div class="col-md-12 text-center">
                <img src="{% static 'imagesreseau/dsi11.png' %}" class="img-responvie" alt="">   
          </div>
         </div>

   </div>
</div>

{% endblock content %}
    

blog/templates/blog/ajoutconfig.html
{% load static %}



{% include 'blog/navbar.html' %}






<link href="{% static 'ajoutconfig/ajoutconfig.css' %}" rel="stylesheet">

<style>
    label{
        display: none;
    }
    .errorlist{
        display: none;
    }
    #id_types{
        width: 460px;
    }
    #id_equipement{
     width: 460px;
    }
    
</style>



{% if title  %}

<title>DSI LaPoste - {{ title }}</title>

{% else %}
  
 <title>DSI LaPoste</title>

 {% endif %}




 
        
{% block  content %}



<center>

        <style>
                body { margin-top: 50px; }
            </style>
 
     
      <!-- Sections -->
            <section id="contact">
                <div id="map"></div>
                {% if send  %}

           reussi
                {% else %}

    
                <div class="container text-center">
                        
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-9 col-md-offset-10 col-sm-12 col-xs-12">
                            <div class="contact-form-area">
                                <form method="POST" enctype="multipart/form-data" action="." class="post-form">{% csrf_token %}



                        <div class="form-group">
                         <label class="control-label col-sm-2" for="equipement">Equipement:</label>
                           <div class="col-sm-10">
                            {{ form.equipement}}
                           </div>
                      </div>             
                                   

                                    
                      <div class="form-group">
                         <label class="control-label col-sm-2" for="types">Types:</label>
                           <div class="col-sm-10">
                               {{ form.types }}
                           </div>
                      </div>

                                
                      
                     <div class="form-group">
                         <label class="control-label col-sm-2" for="description">Description:</label>
                            <div class="col-sm-10">
                                {{ form.description}} 
                            </div>
                     </div>   
                                    

                     <button type="submit"  class="save btn btn-primary col-md-3">ajouter</button>
                                </form>
                            </div>	
                        </div>

                {% endif %}
                    </div>
                </div> <!-- /container -->       
            </section>

          
          
            
</center>


{% endblock content %}





<script src="{% static 'ajoutconfig/ajoutconfig.js' %}" ></script>




{% include 'blog/footer.html' %}

blog/templates/blog/article.html
{% extends "blog/base.html" %}

 {% block content %}

 <style>
  body { margin-top: 201px;
     
   }

  

 </style>
 
 <center>

 <h1>Blog Creation d'article</h1>

 <div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center mb-5">Bootstrap 4 Forms</h2>
            <ul class="nav nav-fill">
                <a class="nav-item" href="#formLogin">Login</a>
                <a class="nav-item" href="#formRegister">Sign-up</a>
                <a class="nav-item" href="#formChangePassword">Password</a>
                <a class="nav-item" href="#formResetPassword">Reset</a>
                <a class="nav-item" href="#formPayment">Payment</a>
                <a class="nav-item" href="#formUserEdit">User</a>
                <a class="nav-item" href="#formContact">Contact</a>
                <a class="nav-item" href="#formComplex">Complex</a>
            </ul>
            <hr class="mb-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <span class="anchor" id="formLogin"></span>

                    <!-- form card login with validation feedback -->
                    <div class="card card-outline-secondary">
                        <div class="card-header">
                            <h3 class="mb-0">Login</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" role="form" autocomplete="off" id="loginForm" novalidate="" method="POST">
                                <div class="form-group">
                                    <label for="uname1">Username</label>
                                    <input type="text" class="form-control" name="uname1" id="uname1" required="">
                                    <div class="invalid-feedback">Please enter your username or email</div>
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" id="pwd1" required="" autocomplete="new-password">
                                    <div class="invalid-feedback">Please enter a password</div>
                                </div>
                                <div class="form-check small">
                                    <label class="form-check-label">
                                        <input type="checkbox" class="form-check-input"> <span>Remember me on this computer</span>
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-success btn-lg float-right" id="btnLogin">Login</button>
                            </form>
                        </div>
                        <!--/card-body-->
                    </div>
                    <!-- /form card login -->

                </div>
                <div class="col-md-6 offset-md-3">
                    <span class="anchor" id="formRegister"></span>
                    <hr class="mb-5">

                    <!-- form card register -->
                    <div class="card card-outline-secondary">
                        <div class="card-header">
                            <h3 class="mb-0">Sign Up</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" role="form" autocomplete="off">
                                <div class="form-group">
                                    <label for="inputName">Name</label>
                                    <input type="text" class="form-control" id="inputName" placeholder="Full name">
                                </div>
                                <div class="form-group">
                                    <label for="inputEmail3">Email</label>
                                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email" required="">
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3">Password</label>
                                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password" required="">
                                </div>
                                <div class="form-group">
                                    <label for="inputVerify3">Verify</label>
                                    <input type="password" class="form-control" id="inputVerify3" placeholder="Password (again)" required="">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-lg float-right">Register</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /form card register -->

                </div>
                
                    </div>

                </div>

            </div>
            <!--/row-->

        <br><br><br><br>

        
        <!--/col-->
  
    <!--/row-->
    <hr>
    <p class="text-center">The End.<br>
        <a class="small text-info d-inline-block" href="https://www.codeply.com/bootstrap-4-examples">More Bootstrap 4 Examples</a>
    </p>
    
</div>
<!--/container-->

</center>

<p></p>
<p></p>
<p></p>


 {% endblock content %}

blog/templates/blog/base.html
{% load static %}



{% include 'blog/navbar.html' %}


<style>
     #content {
    width: 1100px;
}
</style>

<head>
    
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



<!------ Include the above in your HEAD tag ---------->







   {% if title  %}

    <title>DSI LaPoste - {{ title }}</title>

    {% else %}
      
     <title>DSI LaPoste</title>

     {% endif %}

         
</head>
<body>
    








        {% block content %}

       

      

        {% endblock content%}


       
       

        <style>
         footer{ margin-top: 130px; }
        </style>
                    
        





                    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
                    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
                
                    <script language="JavaScript" src="https://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript"></script>
                    <script language="JavaScript" src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
                    <script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>






</body>



{% include 'blog/footer.html' %}

blog/templates/blog/footer.html
 {% load static %}


<link href="{% static 'acceuil/acceuil.css' %}" rel="stylesheet">


<footer class="navbar navbar-fixed-bottom bg-info" class="webintern-footer">

<div class="text-white tt-copy-left">Copyright © LaPoste-DSI 2019. Tous droits réservés. </div>




      <div class="tt-copy-right">
        <div class="text-white">
          <div class=" mt-4 font-weight-bold">crée par MADICKE DIOP Etudiant en Master 1 TDSI</div>
  
          <i class="fas fa-phone mt-3"></i> <a href="tel:+">77 045 42 24</a><br>
          <i class="fa fa-envelope mt-3"></i> <a href="mailto:your-email@your-domain.com">diopmadicke351@gmail.com</a><br>
        
          </div>

        </div>

    








</footer>

blog/templates/blog/maintenance.html
{% extends "blog/base.html" %}

 {% load static %}

 {% block content %}
    

 <style>
   body { margin-top: 201px; }
  </style>

<center>

  <h1>Blog Maintenance</h1>
 
  <div class="container py-5">
     <div class="row">
         <div class="col-md-12">
            <h1 class="text-center mb-5">Tâches Administratives</h1>
             <ul class="nav nav-fill">
                 <a class="nav-item" href="{% url 'listeconfig' %}"><button type="button" class="btn btn-secondary">Liste Equipement</button></a>
                 <a class="nav-item" href="{% url 'ajoutconfig' %}"><button type="button" class="btn btn-secondary">Ajouter Equipement</button></a>
                 <a class="nav-item" href="#formChangePassword"><button type="button" class="btn btn-secondary">Modifier Equipement</button></a>
                 <a class="nav-item" href="#formResetPassword"><button type="button" class="btn btn-secondary">Supprimer Equipement</button></a>
                
             </ul>
             
 
                 </div>
 
             </div>
             <!--/row-->
 
         <br><br><br><br>
 
         
         <!--/col-->
   
     <!--/row-->
     <hr>
     
 </div>
 <!--/container-->



 </center>
 {% endblock content %}




 

blog/templates/blog/navbar.html
{% load static %}




<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">





    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'login/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}" >




{% block content %}   




<style>
        body { margin-top: 130px; }
       </style>





{% if user.is_authenticated %}
  
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-info mb-4">
                
    <div class="container">
                <a class="navbar-brand" href="{% url 'acceuil' %}">
                    <img src="{% static 'image/poste.jpg' %}" width="52" height="36" class="d-inline-block align-top" alt="">DSI
                </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapseLinks" aria-expanded="false" aria-label="Toggle Navigation">
                 <span class="navbar-toggle-icon"> </span>

             </button>   

             <div class="collapse navbar-collapse " id="navbarCollapseLink">

                <ul class="navbar-nav">
                    <li class="nav-item" >
                        <a href="{% url 'acceuil' %}" class="nav-link"> Acceuil </a>
                    </li>



                    <li class="nav-item" >
                     <a href="{% url 'reseau' %}" class="nav-link"> Reseau </a>
                 </li>





                 <li class="nav-item" >
                     <a href="{% url 'maintenance' %}" class="nav-link"> Maintenance </a>
                 </li>

                  
                 
                 <li class="nav-item" >
                     <a href="{% url 'pooldev' %}" class="nav-link"> PoolDev </a>
                 </li>

                  




                </ul>

                
           

    </div>

    <form class="form-inline my-2 my-lg-0">
            <a href="{% url 'users:deconnect' %}" class="btn btn-primary ml-3"> Deconnexion </a>
    </form> 
    
    
 </div>


</nav>

            {% else  %}




      
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-info mb-4">
                
        <div class="container">
                    <a class="navbar-brand" href="{% url 'acceuil' %}">
                        <img src="{% static 'image/poste.jpg' %}" width="52" height="36" class="d-inline-block align-top" alt="">DSI
                    </a>
    
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapseLinks" aria-expanded="false" aria-label="Toggle Navigation">
                     <span class="navbar-toggle-icon"> </span>
    
                 </button>   
    
                 <div class="collapse navbar-collapse " id="navbarCollapseLink">
    
                    <ul class="navbar-nav">
                        <li class="nav-item" >
                            <a href="{% url 'acceuil' %}" class="nav-link"> Acceuil </a>
                        </li>
    
    
    
                        <li class="nav-item" >
                         <a href="{% url 'reseau' %}" class="nav-link"> Reseau </a>
                     </li>
    
    
    
    
    
                     <li class="nav-item" >
                         <a href="{% url 'maintenance' %}" class="nav-link"> Maintenance </a>
                     </li>
    
                      
                     
                     <li class="nav-item" >
                         <a href="{% url 'pooldev' %}" class="nav-link"> PoolDev </a>
                     </li>
    
                      
    
    
    
    
                    </ul>
    
                    
               
    
        </div>
    
      
        <form class="form-inline my-2 my-lg-0">



                <a href="{% url 'users:login' %}" class="btn btn-outline-secondary">  Se connecter </a>
                <a href="{% url 'users:signup' %}" class="btn btn-primary ml-3"> S'inscrire </a>
                 {% endif %}
             </form>
         
        
     </div>
    
    
    </nav>













{% endblock content%}






          


           <!-- JS -->
           <script src="{% static 'login/vendor/jquery/jquery.min.js' %}"></script>
           <script src="{% static 'login/js/main.js' %}" ></script>
   

          





    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

blog/templates/blog/pooldev.html
 
  {% extends "blog/base.html" %}

  {% load static %}
 


 {% block content %}
    

 <style>
   body { margin-top: 201px; }
  </style>

<center>

  <h1>Blog PoolDev</h1>
 
  <div class="container py-5">
     <div class="row">
         <div class="col-md-12">
            <h1 class="text-center mb-5">Tâches Administratives</h1>
             <ul class="nav nav-fill">
                 <a class="nav-item" href="{% url 'listeconfig' %}"><button type="button" class="btn btn-success">Liste Equipement</button></a>
                 <a class="nav-item" href="{% url 'ajoutconfig' %}"><button type="button" class="btn btn-success">Ajouter Equipement</button></a>
                 <a class="nav-item" href="#formChangePassword"><button type="button" class="btn btn-success">Modifier Equipement</button></a>
                 <a class="nav-item" href="#formResetPassword"><button type="button" class="btn btn-success">Supprimer Equipement</button></a>
                
             </ul>
             
 
                 </div>
 
             </div>
             <!--/row-->
 
         <br><br><br><br>
 
         
         <!--/col-->
   
     <!--/row-->
     <hr>
     
 </div>
 <!--/container-->



 </center>
 {% endblock content %}

users/templates/users/login.html
        
        {% load static %}


        {% include 'blog/navbar.html' %}









   
        {% if title  %}

        <title>DSI LaPoste - {{ title }}</title>
    
        {% else %}
          
         <title>DSI LaPoste</title>
    
         {% endif %}
    




{% block content %}   

<center>



    <style>
        body { margin-top: -70px; }
    </style>


<div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'login/images/signin-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'users:signup' %}" class="signup-image-link">Créer un compte</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">S'authentifier</h2>
                        {% if  error %}
                        <div class="alert alert-danger" role="alert">
                                Veuillez vérifier vos infos
                              </div>
                        {% endif %}
                        <form method="POST" class="register-form" id="login-form">
                                {% csrf_token %}
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder="Votre Email"/>
                                {% if  username_error %}
                                <div class="alert alert-danger" role="alert">
                                       Verifier votre adresse email 
                                      </div>
                                {% endif %} 
                            </div>
                            <div class="form-group">
                                <label for="password"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="password" placeholder="Password"/>
                                {% if  password_error %}
                                <div class="alert alert-danger" role="alert">
                                        Mot de trop court,minumun 5 caracteres
                                      </div>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Souviens-toi de moi</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Ou connectez avec</span>
                            
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

</center>

{% endblock %}




{% include 'blog/footer.html' %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load static %}







{% block content %}   

    <div class="content-section">
        <div class="medias">
            <img class="rounded-circle account-img" src="" alt="">
            <div class="media-body">
                <h2 class="media-heading">{{user.name}}</h2>
                <p class="text-secondary">{{user.email}}</p>

            </div>

        </div>
        
    </div>





{% endblock %}